language: python

python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

# Set up our environment
env:
  NOSE_WITH_XUNIT: 1
  NOSE_WITH_COVERAGE: 1
  NOSE_COVER_BRANCHES: 1
  NOSE_COVER_INCLUSIVE: 1
  DJANGO_SETTINGS_MODULE: stackdio.server.settings.testing

# So that we get a docker container
sudo: false

# Make sure our pip install works
addons:
  apt:
    packages:
      - swig

## Customize dependencies
install:
  - npm install -g bower
  - pip install -U pip
  - pip install -U wheel
  - pip install -U -r requirements/testing.txt
  - export STACKDIO_VERSION=`python setup.py --version`

## Customize test commands
before_script:
  - pep8 --ignore=E501,E12 --exclude='*/migrations/*,*/bower_components/*' stackdio/ && echo 'Finished PEP-8 Check Cleanly' || echo 'Finished PEP-8 Check With Errors'
  - pylint --rcfile=.pylintrc stackdio/ && echo 'Finished Pylint Check Cleanly' || echo 'Finished Pylint Check With Errors'
  - mkdir /home/travis/.stackdio
  - cp tests/config-travis /home/travis/.stackdio/config

script:
  - python manage.py test --cover-html
  - python manage.py build_ui

after_script:
  - python setup.py sdist
  - python setup.py bdist_wheel

after_success:
  - coveralls

deploy:
  provider: releases
  api_key:
    secure: bkmap6muMBDHYav/TeeT4g1KTx5Xe+dbyBb44rte/xowQykKEU7VT1a/y2AsbHrWPwM6DnhwyntJcq2YWt/Ug7uPv9SY4DUjsy94u6MHaNzoM6xfsHynMrxO10kYGx9vgEIbexhjCJuIlYfluEkMBEl3E5IIqIrRn1Vb6rXVfeiLbeeHXbFS/aVduyp6ZFeJvuHAuiihm6QKgDMRRhyn5rzWvpeflPL0AYDEh0V+5+eL3Npm7WseyDnXPw6m9O6naK+Ej3bsyA63KDfNykHuSn17ic+Yy3sOMijCbIDxDDBuQAoPn45se4zZhHS4STD00Cf1IxuA7wMaJfc0wChloj3PZ6W2g15iFo/bEnaEl+TnQdS/MMCvu6xg+mX88k8upxLliYXpsQ7tia0Mk2dshRA8corVBi9JLnM+GbLNzGkRkLPkY9L1SquVtxI8oDKUzmqcphFkiia7cJSNEgisfGMTTQ5uoeV6Pw9+MFihuqwEw9lCzREpuJ76zcO51cFugF4hnXWVekgzWFF86NqjvSo3No21OudkhCzvDLDhGq2rdqZiiqKgnSTq7R8oDoRj8ujoPGuCnc7yeAZyG+jhBdLYWcyvCYosWbBcmGLFfdqDOtKyK8skvpMVUULJKAcHAeANLJWv4Td5RIqBXDE9rU/JnPLtgy7Pgvet3TtU8Jk=
  file:
    - dist/stackdio-server-$STACKDIO_VERSION.tar.gz
    - dist/stackdio_server-$STACKDIO_VERSION-py2-none-any.whl
  skip_cleanup: true
  on:
    tags: true
