# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-09 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0007_0_8_0_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprinthostdefinition',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
